<?php
/**
 * BookingApi
 * PHP version 5
 *
 * @category Class
 * @package  YellowWave\SwaggerClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planaday Public API URL
 *
 * This documentation describes the calls available in the public API of planaday.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace YellowWave\SwaggerClient\PlanadaySDK;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use YellowWave\SwaggerClient\ApiException;
use YellowWave\SwaggerClient\Configuration;
use YellowWave\SwaggerClient\HeaderSelector;
use YellowWave\SwaggerClient\ObjectSerializer;

/**
 * BookingApi Class Doc Comment
 *
 * @category Class
 * @package  YellowWave\SwaggerClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BookingApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createBooking
     *
     * Create booking
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  float $course_id ID of the Course to create booking for in the form of an integer (required)
     * @param  \YellowWave\SwaggerClient\Model\BookingCourseIdBody $body body (optional)
     *
     * @throws \YellowWave\SwaggerClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \YellowWave\SwaggerClient\Model\InlineResponse200
     */
    public function createBooking($x_api_key, $course_id, $body = null)
    {
        list($response) = $this->createBookingWithHttpInfo($x_api_key, $course_id, $body);
        return $response;
    }

    /**
     * Operation createBookingWithHttpInfo
     *
     * Create booking
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  float $course_id ID of the Course to create booking for in the form of an integer (required)
     * @param  \YellowWave\SwaggerClient\Model\BookingCourseIdBody $body (optional)
     *
     * @throws \YellowWave\SwaggerClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \YellowWave\SwaggerClient\Model\InlineResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function createBookingWithHttpInfo($x_api_key, $course_id, $body = null)
    {
        $returnType = '\YellowWave\SwaggerClient\Model\InlineResponse200';
        $request = $this->createBookingRequest($x_api_key, $course_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\YellowWave\SwaggerClient\Model\InlineResponse200',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\YellowWave\SwaggerClient\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\YellowWave\SwaggerClient\Model\InlineResponse404',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createBookingAsync
     *
     * Create booking
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  float $course_id ID of the Course to create booking for in the form of an integer (required)
     * @param  \YellowWave\SwaggerClient\Model\BookingCourseIdBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBookingAsync($x_api_key, $course_id, $body = null)
    {
        return $this->createBookingAsyncWithHttpInfo($x_api_key, $course_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createBookingAsyncWithHttpInfo
     *
     * Create booking
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  float $course_id ID of the Course to create booking for in the form of an integer (required)
     * @param  \YellowWave\SwaggerClient\Model\BookingCourseIdBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBookingAsyncWithHttpInfo($x_api_key, $course_id, $body = null)
    {
        $returnType = '\YellowWave\SwaggerClient\Model\InlineResponse200';
        $request = $this->createBookingRequest($x_api_key, $course_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createBooking'
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  float $course_id ID of the Course to create booking for in the form of an integer (required)
     * @param  \YellowWave\SwaggerClient\Model\BookingCourseIdBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createBookingRequest($x_api_key, $course_id, $body = null)
    {
        // verify the required parameter 'x_api_key' is set
        if ($x_api_key === null || (is_array($x_api_key) && count($x_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_api_key when calling createBooking'
            );
        }
        // verify the required parameter 'course_id' is set
        if ($course_id === null || (is_array($course_id) && count($course_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $course_id when calling createBooking'
            );
        }

        $resourcePath = '/booking/{course_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($course_id !== null) {
            $resourcePath = str_replace(
                '{' . 'course_id' . '}',
                ObjectSerializer::toPathValue($course_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteMadeBooking
     *
     * Delete made booking
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  string $booking_id ID of the booking received in the booking post call (i.e API5ce597c40e0fc6.85265205) (required)
     * @param  \YellowWave\SwaggerClient\Model\BookingBookingIdBody $body body (optional)
     *
     * @throws \YellowWave\SwaggerClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \YellowWave\SwaggerClient\Model\InlineResponse2001
     */
    public function deleteMadeBooking($x_api_key, $booking_id, $body = null)
    {
        list($response) = $this->deleteMadeBookingWithHttpInfo($x_api_key, $booking_id, $body);
        return $response;
    }

    /**
     * Operation deleteMadeBookingWithHttpInfo
     *
     * Delete made booking
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  string $booking_id ID of the booking received in the booking post call (i.e API5ce597c40e0fc6.85265205) (required)
     * @param  \YellowWave\SwaggerClient\Model\BookingBookingIdBody $body (optional)
     *
     * @throws \YellowWave\SwaggerClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \YellowWave\SwaggerClient\Model\InlineResponse2001, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteMadeBookingWithHttpInfo($x_api_key, $booking_id, $body = null)
    {
        $returnType = '\YellowWave\SwaggerClient\Model\InlineResponse2001';
        $request = $this->deleteMadeBookingRequest($x_api_key, $booking_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\YellowWave\SwaggerClient\Model\InlineResponse2001',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\YellowWave\SwaggerClient\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\YellowWave\SwaggerClient\Model\InlineResponse404',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteMadeBookingAsync
     *
     * Delete made booking
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  string $booking_id ID of the booking received in the booking post call (i.e API5ce597c40e0fc6.85265205) (required)
     * @param  \YellowWave\SwaggerClient\Model\BookingBookingIdBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteMadeBookingAsync($x_api_key, $booking_id, $body = null)
    {
        return $this->deleteMadeBookingAsyncWithHttpInfo($x_api_key, $booking_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteMadeBookingAsyncWithHttpInfo
     *
     * Delete made booking
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  string $booking_id ID of the booking received in the booking post call (i.e API5ce597c40e0fc6.85265205) (required)
     * @param  \YellowWave\SwaggerClient\Model\BookingBookingIdBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteMadeBookingAsyncWithHttpInfo($x_api_key, $booking_id, $body = null)
    {
        $returnType = '\YellowWave\SwaggerClient\Model\InlineResponse2001';
        $request = $this->deleteMadeBookingRequest($x_api_key, $booking_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteMadeBooking'
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  string $booking_id ID of the booking received in the booking post call (i.e API5ce597c40e0fc6.85265205) (required)
     * @param  \YellowWave\SwaggerClient\Model\BookingBookingIdBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteMadeBookingRequest($x_api_key, $booking_id, $body = null)
    {
        // verify the required parameter 'x_api_key' is set
        if ($x_api_key === null || (is_array($x_api_key) && count($x_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_api_key when calling deleteMadeBooking'
            );
        }
        // verify the required parameter 'booking_id' is set
        if ($booking_id === null || (is_array($booking_id) && count($booking_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $booking_id when calling deleteMadeBooking'
            );
        }

        $resourcePath = '/booking/{booking_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($booking_id !== null) {
            $resourcePath = str_replace(
                '{' . 'booking_id' . '}',
                ObjectSerializer::toPathValue($booking_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation markBookingAsPayed
     *
     * Mark booking as payed
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  string $booking_id ID of the booking received in the booking post call (i.e API5ce597c40e0fc6.85265205) (required)
     * @param  \YellowWave\SwaggerClient\Model\PayedBookingIdBody $body body (optional)
     *
     * @throws \YellowWave\SwaggerClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \YellowWave\SwaggerClient\Model\InlineResponse2001
     */
    public function markBookingAsPayed($x_api_key, $booking_id, $body = null)
    {
        list($response) = $this->markBookingAsPayedWithHttpInfo($x_api_key, $booking_id, $body);
        return $response;
    }

    /**
     * Operation markBookingAsPayedWithHttpInfo
     *
     * Mark booking as payed
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  string $booking_id ID of the booking received in the booking post call (i.e API5ce597c40e0fc6.85265205) (required)
     * @param  \YellowWave\SwaggerClient\Model\PayedBookingIdBody $body (optional)
     *
     * @throws \YellowWave\SwaggerClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \YellowWave\SwaggerClient\Model\InlineResponse2001, HTTP status code, HTTP response headers (array of strings)
     */
    public function markBookingAsPayedWithHttpInfo($x_api_key, $booking_id, $body = null)
    {
        $returnType = '\YellowWave\SwaggerClient\Model\InlineResponse2001';
        $request = $this->markBookingAsPayedRequest($x_api_key, $booking_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\YellowWave\SwaggerClient\Model\InlineResponse2001',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\YellowWave\SwaggerClient\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\YellowWave\SwaggerClient\Model\InlineResponse404',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation markBookingAsPayedAsync
     *
     * Mark booking as payed
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  string $booking_id ID of the booking received in the booking post call (i.e API5ce597c40e0fc6.85265205) (required)
     * @param  \YellowWave\SwaggerClient\Model\PayedBookingIdBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function markBookingAsPayedAsync($x_api_key, $booking_id, $body = null)
    {
        return $this->markBookingAsPayedAsyncWithHttpInfo($x_api_key, $booking_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation markBookingAsPayedAsyncWithHttpInfo
     *
     * Mark booking as payed
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  string $booking_id ID of the booking received in the booking post call (i.e API5ce597c40e0fc6.85265205) (required)
     * @param  \YellowWave\SwaggerClient\Model\PayedBookingIdBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function markBookingAsPayedAsyncWithHttpInfo($x_api_key, $booking_id, $body = null)
    {
        $returnType = '\YellowWave\SwaggerClient\Model\InlineResponse2001';
        $request = $this->markBookingAsPayedRequest($x_api_key, $booking_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'markBookingAsPayed'
     *
     * @param  string $x_api_key e.g. &lt;apikey&gt; (required)
     * @param  string $booking_id ID of the booking received in the booking post call (i.e API5ce597c40e0fc6.85265205) (required)
     * @param  \YellowWave\SwaggerClient\Model\PayedBookingIdBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function markBookingAsPayedRequest($x_api_key, $booking_id, $body = null)
    {
        // verify the required parameter 'x_api_key' is set
        if ($x_api_key === null || (is_array($x_api_key) && count($x_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_api_key when calling markBookingAsPayed'
            );
        }
        // verify the required parameter 'booking_id' is set
        if ($booking_id === null || (is_array($booking_id) && count($booking_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $booking_id when calling markBookingAsPayed'
            );
        }

        $resourcePath = '/booking/payed/{booking_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($booking_id !== null) {
            $resourcePath = str_replace(
                '{' . 'booking_id' . '}',
                ObjectSerializer::toPathValue($booking_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
