<?php
/**
 * BookingcourseIdStudentsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YellowWave
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planaday Public API URL
 *
 * This documentation describes the calls available in the public API of planaday.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YellowWave;

use PHPUnit\Framework\TestCase;

/**
 * BookingcourseIdStudentsTest Class Doc Comment
 *
 * @category    Class
 * @description BookingcourseIdStudents
 * @package     YellowWave
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BookingcourseIdStudentsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BookingcourseIdStudents"
     */
    public function testBookingcourseIdStudents()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "initials"
     */
    public function testPropertyInitials()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "house_number"
     */
    public function testPropertyHouseNumber()
    {
    }

    /**
     * Test attribute "house_number_extension"
     */
    public function testPropertyHouseNumberExtension()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "phonenumber"
     */
    public function testPropertyPhonenumber()
    {
    }

    /**
     * Test attribute "date_of_birth"
     */
    public function testPropertyDateOfBirth()
    {
    }

    /**
     * Test attribute "employee_id"
     */
    public function testPropertyEmployeeId()
    {
    }

    /**
     * Test attribute "costcentercode"
     */
    public function testPropertyCostcentercode()
    {
    }

    /**
     * Test attribute "company_position"
     */
    public function testPropertyCompanyPosition()
    {
    }

    /**
     * Test attribute "is_contact_person"
     */
    public function testPropertyIsContactPerson()
    {
    }

    /**
     * Test attribute "is_student"
     */
    public function testPropertyIsStudent()
    {
    }

    /**
     * Test attribute "internal_reference"
     */
    public function testPropertyInternalReference()
    {
    }

    /**
     * Test attribute "remark"
     */
    public function testPropertyRemark()
    {
    }
}
