<?php
/**
 * BookingCourseIdBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YellowWave
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planaday Public API URL
 *
 * This documentation describes the calls available in the public API of planaday.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YellowWave;

use PHPUnit\Framework\TestCase;

/**
 * BookingCourseIdBodyTest Class Doc Comment
 *
 * @category    Class
 * @description BookingCourseIdBody
 * @package     YellowWave
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BookingCourseIdBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BookingCourseIdBody"
     */
    public function testBookingCourseIdBody()
    {
    }

    /**
     * Test attribute "students"
     */
    public function testPropertyStudents()
    {
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "creating_source"
     */
    public function testPropertyCreatingSource()
    {
    }

    /**
     * Test attribute "course_id"
     */
    public function testPropertyCourseId()
    {
    }

    /**
     * Test attribute "dayparts"
     */
    public function testPropertyDayparts()
    {
    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {
    }
}
