<?php
/**
 * InlineResponse2006LinksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YellowWave\SwaggerClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planaday Public API URL
 *
 * This documentation describes the calls available in the public API of planaday.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YellowWave\SwaggerClient;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2006LinksTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2006Links
 * @package     YellowWave\SwaggerClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2006LinksTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2006Links"
     */
    public function testInlineResponse2006Links()
    {
    }

    /**
     * Test attribute "self"
     */
    public function testPropertySelf()
    {
    }

    /**
     * Test attribute "first"
     */
    public function testPropertyFirst()
    {
    }

    /**
     * Test attribute "last"
     */
    public function testPropertyLast()
    {
    }

    /**
     * Test attribute "previous"
     */
    public function testPropertyPrevious()
    {
    }

    /**
     * Test attribute "next"
     */
    public function testPropertyNext()
    {
    }
}
