<?php
/**
 * InlineResponse2002Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  YellowWave
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planaday Public API URL
 *
 * This documentation describes the calls available in the public API of planaday.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YellowWave;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2002Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2002
 * @package     YellowWave
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2002"
     */
    public function testInlineResponse2002()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "href"
     */
    public function testPropertyHref()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "daypart_amount"
     */
    public function testPropertyDaypartAmount()
    {
    }

    /**
     * Test attribute "dayparts"
     */
    public function testPropertyDayparts()
    {
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
    }

    /**
     * Test attribute "costs"
     */
    public function testPropertyCosts()
    {
    }

    /**
     * Test attribute "coursetemplate"
     */
    public function testPropertyCoursetemplate()
    {
    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {
    }

    /**
     * Test attribute "level_description"
     */
    public function testPropertyLevelDescription()
    {
    }

    /**
     * Test attribute "start_guaranteed"
     */
    public function testPropertyStartGuaranteed()
    {
    }

    /**
     * Test attribute "moneyback_guaranteed"
     */
    public function testPropertyMoneybackGuaranteed()
    {
    }

    /**
     * Test attribute "has_elearning"
     */
    public function testPropertyHasElearning()
    {
    }

    /**
     * Test attribute "has_code95"
     */
    public function testPropertyHasCode95()
    {
    }

    /**
     * Test attribute "has_soob"
     */
    public function testPropertyHasSoob()
    {
    }

    /**
     * Test attribute "has_stap"
     */
    public function testPropertyHasStap()
    {
    }

    /**
     * Test attribute "stap_only"
     */
    public function testPropertyStapOnly()
    {
    }

    /**
     * Test attribute "labels"
     */
    public function testPropertyLabels()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "extrafields"
     */
    public function testPropertyExtrafields()
    {
    }

    /**
     * Test attribute "repeating_courses"
     */
    public function testPropertyRepeatingCourses()
    {
    }
}
