<?php
/**
 * InlineResponse2007AddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YellowWave\SwaggerClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planaday Public API URL
 *
 * This documentation describes the calls available in the public API of planaday.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YellowWave\SwaggerClient;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2007AddressTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2007Address
 * @package     YellowWave\SwaggerClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2007AddressTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2007Address"
     */
    public function testInlineResponse2007Address()
    {
    }

    /**
     * Test attribute "street_1"
     */
    public function testPropertyStreet1()
    {
    }

    /**
     * Test attribute "street_2"
     */
    public function testPropertyStreet2()
    {
    }

    /**
     * Test attribute "housenumber"
     */
    public function testPropertyHousenumber()
    {
    }

    /**
     * Test attribute "housenumber_extension"
     */
    public function testPropertyHousenumberExtension()
    {
    }

    /**
     * Test attribute "zipcode"
     */
    public function testPropertyZipcode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "lat"
     */
    public function testPropertyLat()
    {
    }

    /**
     * Test attribute "lng"
     */
    public function testPropertyLng()
    {
    }
}
