<?php
/**
 * InlineResponse2005MetaPageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YellowWave
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planaday Public API URL
 *
 * This documentation describes the calls available in the public API of planaday.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YellowWave;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2005MetaPageTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2005MetaPage
 * @package     YellowWave
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2005MetaPageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2005MetaPage"
     */
    public function testInlineResponse2005MetaPage()
    {
    }

    /**
     * Test attribute "current"
     */
    public function testPropertyCurrent()
    {
    }

    /**
     * Test attribute "offset"
     */
    public function testPropertyOffset()
    {
    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }
}
