<?php
/**
 * InstructorIdCourseBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YellowWave
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planaday Public API URL
 *
 * This documentation describes the calls available in the public API of planaday.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace YellowWave;

use PHPUnit\Framework\TestCase;

/**
 * InstructorIdCourseBodyTest Class Doc Comment
 *
 * @category    Class
 * @description InstructorIdCourseBody
 * @package     YellowWave
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InstructorIdCourseBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InstructorIdCourseBody"
     */
    public function testInstructorIdCourseBody()
    {
    }

    /**
     * Test attribute "course_id"
     */
    public function testPropertyCourseId()
    {
    }

    /**
     * Test attribute "create_task"
     */
    public function testPropertyCreateTask()
    {
    }

    /**
     * Test attribute "notify"
     */
    public function testPropertyNotify()
    {
    }

    /**
     * Test attribute "include_ical"
     */
    public function testPropertyIncludeIcal()
    {
    }
}
