<?php
/**
 * CourseApiTest
 * PHP version 5
 *
 * @category Class
 * @package  YellowWave
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planaday Public API URL
 *
 * This documentation describes the calls available in the public API of planaday.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace YellowWave;

use YellowWave\Configuration;
use YellowWave\ApiException;
use YellowWave\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CourseApiTest Class Doc Comment
 *
 * @category Class
 * @package  YellowWave
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CourseApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAListOfCourses
     *
     * Get a list of courses.
     *
     */
    public function testGetAListOfCourses()
    {
    }

    /**
     * Test case for viewCourseDetail
     *
     * View Course Detail.
     *
     */
    public function testViewCourseDetail()
    {
    }

    /**
     * Test case for viewListOfDaypartsOfCourse
     *
     * View list of dayparts of Course.
     *
     */
    public function testViewListOfDaypartsOfCourse()
    {
    }

    /**
     * Test case for viewListOfImagesOfCourse
     *
     * View list of images of Course.
     *
     */
    public function testViewListOfImagesOfCourse()
    {
    }

    /**
     * Test case for viewListOfMaterialsOfCourse
     *
     * View list of materials of Course.
     *
     */
    public function testViewListOfMaterialsOfCourse()
    {
    }
}
