<?php
/**
 * InstructorApiTest
 * PHP version 5
 *
 * @category Class
 * @package  YellowWave
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planaday Public API URL
 *
 * This documentation describes the calls available in the public API of planaday.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace YellowWave;

use YellowWave\Configuration;
use YellowWave\ApiException;
use YellowWave\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InstructorApiTest Class Doc Comment
 *
 * @category Class
 * @package  YellowWave
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstructorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addplanAnInstructorToASpecificDaypart
     *
     * Add/plan an instructor to a specific daypart.
     *
     */
    public function testAddplanAnInstructorToASpecificDaypart()
    {
    }

    /**
     * Test case for addplanAnInstructorToAllDaypartsInASpecificCourse
     *
     * Add/plan an instructor to all dayparts in a specific course.
     *
     */
    public function testAddplanAnInstructorToAllDaypartsInASpecificCourse()
    {
    }

    /**
     * Test case for removeunplanAnInstructorFromASpecificDaypart
     *
     * Remove/unplan an instructor from a specific daypart.
     *
     */
    public function testRemoveunplanAnInstructorFromASpecificDaypart()
    {
    }

    /**
     * Test case for removeunplanAnInstructorFromAllDaypartsInASpecificCourse
     *
     * Remove/unplan an instructor from all dayparts in a specific course.
     *
     */
    public function testRemoveunplanAnInstructorFromAllDaypartsInASpecificCourse()
    {
    }

    /**
     * Test case for viewListOfInstructors
     *
     * View list of instructors.
     *
     */
    public function testViewListOfInstructors()
    {
    }
}
